### ISSUE TITLE
Port 0install to lablgtk3

### ISSUE THREAD

**Issue by XVilka** [0install/0install#110]
GTK 2 is being deprecated, and there is largely compatible version of OCaml bindings to GTK 3 is available - [lablgtk3](http://opam.ocaml.org/packages/lablgtk3/).

See lablgtk3 branch here: https://github.com/garrigue/lablgtk/tree/lablgtk3

**Comment by talex5** [comment]
We should do this eventually, but lablgtk3 is still in beta. Also 0install can't be updated to use it until a stable version has been packaged by the target Linux distributions (Debian, Fedora, etc).

Searching for `lablgtk` on https://pkgs.org shows the current state (can't link to the search results for some reason).

**Comment by talex5** [comment]
However, I did try a port to check that it works. https://github.com/garrigue/lablgtk/issues/69 (can't set tooltips on status icons) seems to be the only thing that needs fixing. I also noticed https://github.com/garrigue/lablgtk/issues/68, but that's easy to fix at our end.

There are some minor layout/style problems, but it seems to work.

**Comment by XVilka** [comment]
If it is an issue with lablgtk3, then it is better to report it now, because the first stable release is going to be done soon - https://github.com/garrigue/lablgtk/issues/90

**Comment by talex5** [comment]
Fixed in #148.
