### ISSUE TITLE
JSON API not working on Linux

### ISSUE THREAD

**Issue by bastianeicher** [0install/0install#174]
I've only used the [JSON API](https://docs.0install.net/developers/json-api/) on Windows so far (for Zero Install for Windows). When I tried using it on Linux I ran into a problem.

When sending this command to `0install slave 2.7`:
```
0x5d
["invoke", "1", "select", [{"interface": "https://apps.0install.net/utils/gnupg.xml"}, false]]
```

The process crashed with:
```
Yojson.Json_error("Line 1, bytes 92-93:\nUnexpected end of input")
Raised at file "map.ml", line 135, characters 10-25
Called from file "sexp_conv.ml", line 156, characters 10-37
```

I tested this with 0install 2.10 on Ubuntu 16.04 and 0install 2.15.2 on Ubuntu 20.10.

**Comment by talex5** [comment]
The length should be 5e (or 5f if you include a newline) by my count:
```
$ python
>>> hex(len('["invoke", "1", "select", [{"interface": "https://apps.0install.net/utils/gnupg.xml"}, false]]\n'))
'0x5f'
```

**Comment by bastianeicher** [comment]
You're right, that was the problem. Thanks!
I just copied the sample from the docs, without checking the length. I've updated it: 0install/docs@5c3fa05fc20a5362fff665fdd8fe25bdbf97aac1
