### ISSUE TITLE
Assertion failure in 0install/src/solver/sat.ml, line 602

### ISSUE THREAD

**Issue by NathanReb** [0install/0install#179]
I just ran into this assertion failure when using opam-monorepo. It might very well be the case that the bug actually comes from the way we use `opam-0install` in `opam-monorepo` or from `opam-0install` itself but this seemed like the best place to report this and ask for guidance.

I'm not super familiar with 0install's codebase so I wanted to know if you have any idea what could cause this assertion to fail.

Here's the exception backtrace I got, all of opam-monorepo's dependency or vendored, hence the `duniverse/` prefix:
```
opam-monorepo: internal error, uncaught exception:
               "Assert_failure duniverse/0install/src/solver/sat.ml:602:6"
               Raised at file "duniverse/0install/src/solver/sat.ml", line 602, characters 6-70
               Called from file "duniverse/0install/src/solver/solver_core.ml", line 376, characters 6-42
               Called from file "list.ml", line 110, characters 12-15
               Called from file "list.ml", line 110, characters 12-15
               Called from file "duniverse/0install/src/solver/solver_core.ml", line 77, characters 6-16
               Called from file "duniverse/0install/src/solver/solver_core.ml", line 348, characters 21-41
               Called from file "list.ml", line 110, characters 12-15
               Called from file "list.ml", line 110, characters 12-15
               Called from file "duniverse/0install/src/solver/solver_core.ml", line 77, characters 6-16
               Called from file "duniverse/0install/src/solver/solver_core.ml" (inlined), line 455, characters 26-76
               Called from file "duniverse/0install/src/solver/solver_core.ml", line 463, characters 40-58
               Called from file "duniverse/0install/src/solver/solver_core.ml", line 538, characters 40-78
               Called from file "duniverse/opam-0install-solver/lib/solver.ml", line 23, characters 10-50
               Called from file "lib/opam_solve.ml", line 83, characters 15-62
               Called from file "lib/opam_solve.ml", line 106, characters 2-108
               Called from file "cli/lock.ml", line 119, characters 2-93
               Called from file "duniverse/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
               Called from file "duniverse/cmdliner/src/cmdliner.ml", line 33, characters 27-34
               Called from file "duniverse/cmdliner/src/cmdliner.ml", line 117, characters 32-39
```

We use the following versions of the relevant packages: `0install-solver.2.17`, `opam-0install.0.4`.

Thanks!

**Comment by talex5** [comment]
Yeah, it's not a great error! I seem to recall it happens if you specify that something conflicts with itself, which doesn't make sense.

e.g. if package A1 conflicts with two versions of library B (B1 and B2) then we do:

    at_most_one [A1; B1; B2]

But if A1 (explicitly) conflicts with A1, then you'd get this error due to:

    at_most_one [A1; A1]

**Comment by NathanReb** [comment]
Ok I'll investigate see if I can spot any such conflict. Does It have to be a direct conflict and not a transitive one ?

**Comment by talex5** [comment]
Yes, it has to be direct. And it must be a `conflicts` or a `depopt` too.

(you could also try enabling the commented-out debug line at the start of `Sat.at_most_one`, though you might need to update the `string_of_lits` to `pp_lits`)
