### ISSUE TITLE
MacOS package outdated

### ISSUE THREAD

**Issue by pkoppstein** [0install/0install#182]
I attempted to update my MacOS installation of 0install using the "Get Zero
Install" button at https://0install.net/ but this results in failure:

```
The installation failed. The installer could not install the software.
The installer could not install the software because there was no software found to install.
```

Note that the above-mentioned button leads to
https://sourceforge.net/projects/zero-install/files/0install/2.8/ZeroInstall.pkg/download?use_mirror=newcontinuum

I noticed the above link has "2.8" in it, whereas the homebrew version is numbered "2.17".

**Comment by bastianeicher** [comment]
Thanks for reporting this problem. The Zero Install `.pkg` version is indeed quite outdated. Unfortunately we currently have no one experienced with MacOS packaging working on this (volunteers welcome!).

I've updated the download button on the website to point to an up-to-date MacOS build packaged as a `.tar.bz2` archive instead.

You can manually download and extract it. You can also install it like this:
```
curl -O https://get.0install.net/0install.sh && chmod +x 0install.sh
./0install.sh
```

Of course, using Homebrew should work as well.

**Comment by pkoppstein** [comment]
@bastianeicher - Thanks for the response.  The `curl` method works, but as of this writing, the "Download" button at https://0install.net/ still leads to failure on my MacOS, as though somehow the update you mentioned was not properly propagated.
