### ISSUE TITLE
0install add behind proxy

### ISSUE THREAD

**Issue by a359089** [0install/0install#183]
I am trying to install jq using 0install on redhat linux 7 VM behind Company firewall

This is what I get -

$ ./bin/0install add jq https://apps.0install.net/utils/jq.xml
warning: HTTP GET of https://apps.0install.net/utils/jq.xml failed: No IP address found for hostname "http"
Raised at file "map.ml", line 135, characters 10-25
Called from file "sexp_conv.ml", line 156, characters 10-37

warning: Feed https://apps.0install.net/utils/jq.xml: HTTP GET of https://apps.0install.net/utils/jq.xml failed: No IP address found for hostname "http"
warning: HTTP GET of http://roscidus.com/0mirror/feeds/https/apps.0install.net/utils%23jq.xml/latest.xml failed: No IP address found for hostname "http"
Raised at file "map.ml", line 135, characters 10-25
Called from file "sexp_conv.ml", line 156, characters 10-37

Can't find all required implementations:
- https://apps.0install.net/utils/jq.xml -> (problem)
    Main feed 'https://apps.0install.net/utils/jq.xml' not available
    No known implementations at all

I have already set up env variables http_proxy and https_proxy. Manually run wget  https://apps.0install.net/utils/jq.xml works fine
--2021-08-14 17:24:46--  https://apps.0install.net/utils/jq.xml
Resolving xxx
Connecting to xxx... connected.
Proxy request sent, awaiting response... 200 OK
Length: 13195 (13K) [application/xml]
Saving to: ‘jq.xml’

100%[====================================================================================================================================================================>] 13,195      --.-K/s   in 0.001s

Part of error message is  No IP address found for hostname "http".  But I do not know where to look for this obviously wrong hostname.

**Comment by talex5** [comment]
Maybe you have an `http:` at the start of `https_proxy`'s value or something? Running with `-vv` will get you some verbose output, which might provide more hints...

**Comment by a359089** [comment]
Thx for reply. I decided to take a different approach going with epel route and that went smoothly.
