### ISSUE TITLE
Documentation regarding how to request a new package

### ISSUE THREAD

**Issue by pkoppstein** [0install/0install#184]
ABAICT, the "support" page (https://0install.net/support.html) does not explain how a request to add a new 0Install "feed" should be made.  For example, I'd like to request that "gojq" be added, but am not sure how to make that request most usefully.

**Comment by bastianeicher** [comment]
The best place request a new feed is the [issue tracker for apps.0install.net](https://github.com/0install/apps/issues). Pull requests are of course also very welcome. Docs on how to create feeds can be found [here](https://docs.0install.net/packaging/).

I have updated the support page to directly link to some of the most important issue trackers.
