### ISSUE TITLE
Add a `--yes` option to add

### ISSUE THREAD

**Issue by robin-moss** [0install/0install#189]
Trying to use 0install tools in an automated way doesn't seem possible at the moment because I cannot install `0template`

```
$ yes Y | 0install add 0template http://0install.net/tools/0template.xml
- python3
[Y/N] Warning: interface http://0install.net/tools/0template.xml has been replaced by https://apps.0install.net/0install/0template.xml
```

I can't see anything on the help about doing this either. Could you add a `--yes` option, please?

**Comment by bastianeicher** [comment]
Using the new URL (`0install add 0template https://apps.0install.net/0install/0template.xml)` will get rid of the warning. I've updated the URL in the docs: 0install/docs@ab29c1400d67b403d784fc4d4e8c6de2386332cd

The `- python3 [Y/N]` output looks like 0install is asking whether to use the distribution's native package manager to install Python 3. This is probably not something that should be happening automatically/implicitly. Perhaps you can add this as a separate step in you script before calling `0install`?

FYI: There is a command-line switch `--batch`, available only on Windows so far though. This uses "safe" default answers for most interactive questions and suppresses output ill-suited to automation.

**Comment by robin-moss** [comment]
@bastianeicher thanks, installing Python3 first helped.

I didn't do this locally as when running from my local machine 0install installed Python3 even though it's already installed locally on my Ubuntu 20 machine (or at least it looked like it install Python3.8 specifically for 0install).

Is there a good place to ask a general question/advice on using 0install for our usecase?
