### ISSUE TITLE
Support for credentials?

### ISSUE THREAD

**Issue by robin-moss** [0install/0install#190]
Is it possible to use a URL that requires credentials without putting the username/password in plain text for the URL?

I cannot see anything in the help, or on the docs site.

The use case is that we want to use an internal repo that requires authentication to access. Locally I have things like a `.netrc` setup which tends to authenticate most system but no luck with 0install

**Comment by bastianeicher** [comment]
Actually 0install should respect the `.netrc` file:

https://github.com/0install/0install/blob/22eebdbe51a9f46cda29eed3e9e02e37e36b2d18/src/zeroinstall/http.curl.ml#L151-L158

@talex5 Is there something missing here?

**Comment by talex5** [comment]
The generic binaries are compiled with cohttp instead of curl I think. But it should work if compiled for cohttp, which is what e.g. the Debian packages do.

**Comment by robin-moss** [comment]
Ok, so it should work with netrc. Is there support for credentials on windows?

I'm asking as I cannot find anything in the documentation about how to deal with URLs that need auth

**Comment by bastianeicher** [comment]
Zero Install for Windows uses the Windows Credential Manager for URLs that need authentication. This means the first time a download is attempted from such an URL a dialog box asking for username and password is shown along with a "Remember these credentials" checkbox.

**Comment by robin-moss** [comment]
Thanks for the information
