### ISSUE TITLE
does the packages use mount point ?

### ISSUE THREAD

**Issue by lucasmz1** [0install/0install#206]
I have a few doubts about your package management.
first: does it use mount point like appimage on the system to run apps?
second: where can I learn how to pack an app?
third: Is it like appimage appdir, I mean the packing procedure?
fourth: can I pack and use packages locally?
thank you!

**Comment by bastianeicher** [comment]
> does it use mount point like appimage on the system to run apps?

No, Zero Install doesn't use mount points.

Specific versions of apps and their dependencies (called "implementations") are downloaded into separate directories. The app is then made aware of these directories using environment variables.

For example, a 0install feed might contain the following snippet:

```xml
<requires interface="https://apps.0install.net/lib/png12-0.xml">
  <environment insert="usr/lib" name="LD_LIBRARY_PATH"/>
</requires>
```
This will tell 0install to download a suitable version of `libpng12-0` and put in that app's `LD_LIBRARY_PATH`, without affecting any other apps on the system.

> where can I learn how to pack an app?

You can find the packaging docs here: https://docs.0install.net/packaging/

> Is it like appimage appdir, I mean the packing procedure?

The biggest difference between packaging for 0install and for other package managers, is that 0install doesn't require you to publish new binaries/archives. Instead you only create XML files (called feeds) that point to regular tarballs, ZIP archives, etc. and describe how to extract and combine them (mainly using environment variables).

> can I pack and use packages locally?

Yes, 0install feeds can be both run from an HTTP(S) URL or from a local file.

**Comment by lucasmz1** [comment]
thank you! closing this issue.
