### ISSUE TITLE
Support for .7z (7zip) archives

### ISSUE THREAD

**Issue by BenoitJGirard** [0install/0install#35]
Then we could have 0install feeds for MinGW-w64, its official binaries are compressed using 7zip: http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/ .

**Comment by bastianeicher** [comment]
The [Windows version of Zero Install](http://0install.de/downloads/) already has 7zip support:
```xml
<archive type="application/x-7z-compressed" ... />
```
The Linux does not support 7zip archives yet, but I suppose that would not matter for MinGW releases anyway.

@talex5 Would mind adding `application/x-7z-compressed` to MIME types listed in the [feed specification](http://0install.net/interface-spec.html)?

**Comment by talex5** [comment]
@bastianeicher OK, I've added it to the spec.

I'll close this, as it doesn't sound like it's needed on Linux. If it is, the place to add it would be in https://github.com/0install/0install/blob/master/ocaml/zeroinstall/archive.ml
