### ISSUE TITLE
Warn: gpg: conversion from uft-8 to cp950 failed: illegal byte sequence

### ISSUE THREAD

**Issue by falcon0125** [0install/0install#36]
Win 8.1 64bit (traditional chinese)+ Zero install v2.7.3 

It happened  when i was installing dispcalGUI, 
it shows 
  Warn: gpg: conversion from uft-8 to cp950 failed: illegal byte sequence

Then Fetal error occors when i run dispcalGUI
![fetal error](https://cloud.githubusercontent.com/assets/854189/6772814/1d74c384-d141-11e4-869d-146a82823a37.JPG)

**Comment by bastianeicher** [comment]
I have seen the message `Warn: gpg: conversion from uft-8 to cp950 failed: illegal byte sequence` in logs from other Chinese Windows installations as well. GnuPG seems to translate a string internally encoded as UTF8 to the system's current ANSI codepage (in this case 950 for Big5, a Chinese character encoding method) before outputting it to stdout.

I am not yet sure which string is causing the problem and how to fix.
Could you run this on the command line and see if shows the same warning?
`0install run http://repo.roscidus.com/security/gnupg`

The problem in dispcalGUI is probably an unrelated issue. I have notified a dispcalGUI developer to see if he can help with this.

**Comment by fhoech** [comment]
I don't know what the chinese characters mean, but the closest english error message seems to be "DLL load failed: %1 is not a valid Win32 application". According to stackoverflow, this error occurs when a 64-bit process tries to load a 32-bit DLL. What confuses me is that I don't see how this could happen, as the Python executable and DLLs provided by the feeds used by dispcalGUI are 32-bit. The only thing I can think of is a 64-bit python with 64-bit pywin32 DLLs are already installed on the system, and are somehow shadowing the 32-bit versions provided via the feeds. I have no idea if that's even possible though.

**Comment by falcon0125** [comment]
@bastianeicher 
`0install run http://repo.roscidus.com/security/gnupg` runs smoothly
@fhoech 
I do have installed 64bit python2.7 and 64bit pywin32 on my computer. 
So i try to change my python27 folder name into something else.
And I works!!
May be i'll try standalone version of dispcalGUI

**Comment by fhoech** [comment]
I believe the dispcalGUI problem is now fixed. Please do the following:
- Launch Zero Install
- Click the small down arrow next to "Update all" and select "Update and clean up"
The underlying problem was as I suspected, a system-installed pywintypes27.dll and pythoncom27.dll was used by pywin32. It was necessary to alter win32\lib\pywintypes.py to look for the DLLs in sys.path instead.

**Comment by falcon0125** [comment]
@fhoech  It works! Thank you for fix it so quickly!!
