### ISSUE TITLE
how to "make" from source code only the command line tools, without installing the Gtk tools or dependencies

### ISSUE THREAD

**Issue by zaxebo1** [0install/0install#41]
When i download 0install-2.8.tar.bz2 source from http://0install.net/install-source.html
and then "make" it then it depends upon gtk . 
Can i somehow build only the commandline tools of 0install , without the gtk dependencies .

(In ubuntu-server sense, (say) I want to use "apt-get" command line tool, but not "Software Center" GUI; in the same way can I just build the 0install without GTK dependencies)

That will drastically reduce lots of dependencies of 0install binary (as seen by "ldd 0install" )

****

Hence, i should issue what target of makefile to build only non-gtk tools,as mentioned above

 ````
   make ????
````

**Comment by afb** [comment]
You will find that the gtk dependencies are from the "gui_gtk.cmxs", and not from the "0install" binary which mostly depends on libcurl. Otherwise it's mostly a question if your opamroot has lablgtk or not.

**Comment by afb** [comment]
Also it is easy to get fooled by ldd, as it shows *all* dependencies. If you use `readelf -d` or `objdump -p` instead, you will see that all those extra libraries list actually come from libcurl.so and not from 0install.

**Comment by talex5** [comment]
Yes, the GTK dependencies are limited to the plugin it builds, because the binary needs to work on systems which don't have GTK available at runtime.

Also, if the lablgtk library isn't available at compile time then the GTK plugin won't be built at all. The build-time test for GTK is in `myocamlbuild.ml`:

https://github.com/0install/0install/blob/42e9fcf6debee1cc595c37f102a7cf0cb21fd858/ocaml/myocamlbuild.ml#L105

**Comment by afb** [comment]
Seems like we could need a "compatibility" build, that would bundle *everything* (i.e. libcurl + deps).
We (me) did some backports like that with the Python version, for old Debians with ancient pythons.

Anyway, the actual dependencies ("NEEDED") doesn't seem **that** bad - other than [cURL](http://curl.haxx.se/libcurl/) that is:
```
Dynamic Section:
  NEEDED               libpthread.so.0
  NEEDED               libcurl.so.4
  NEEDED               libm.so.6
  NEEDED               libdl.so.2
  NEEDED               libc.so.6

Version References:
  required from libm.so.6:
    0x09691a75 0x00 06 GLIBC_2.2.5
  required from libc.so.6:
    0x06969191 0x00 12 GLIBC_2.11
  required from libpthread.so.0:
    0x09691972 0x00 11 GLIBC_2.3.2
  required from libdl.so.2:
    0x09691a75 0x00 02 GLIBC_2.2.5
```
Building the GUI module for e.g. GTK+ 2.10 (EL5 version) is probably not *impossible* to do either ?

**Comment by talex5** [comment]
Note that curl depends on libssl, which depends on the CA certificates package too. Actually replacing these with pure OCaml versions would be quite easy:

- <https://github.com/mirage/ocaml-cohttp>
- <https://github.com/mirleft/ocaml-tls>

But it would be nice to use the distribution's list of trusted CAs, if available, as it's more likely to stay up-to-date.

Whether statically linking the TLS library is good or bad for security is unclear to me: we won't benefit from the frequent patches made to openssl, but on the other hand, ocaml-tls is probably less buggy in the first place...
