### ISSUE TITLE
Could you fix the link on feed for libreoffice, please?

### ISSUE THREAD

**Issue by bvaschenko** [0install/0install#42]
This link doesn't work:
http://0install.area9innovation.com/0install/packages/libreoffice/libreoffice.xml
Stable version is 4.4.4 instead of 4.4.3:

Index of /libreoffice/stable
 	Name	Last modified	Size	Metadata
 	Parent Directory	 	-	 
 	4.3.7/	25-Apr-2015 08:39	-	 
 	4.4.4/	30-Jun-2015 10:46	-	 
Apache Server at download.documentfoundation.org Port 80

**Comment by talex5** [comment]
Don't know anything about that site. Try <http://0install.de/feeds/LibreOffice.xml>:

    $ 0install search libreoffice
    http://0install.de/feeds/LibreOffice.xml                                           
      LibreOffice - a free office suite [100%]
