### ISSUE TITLE
upcoming fedora 23 package of 0install is still 2.3

### ISSUE THREAD

**Issue by zaxebo1** [0install/0install#43]
disclaimer: I know that this is not an issue with 0install project, but is an issue with fedora packaging. But I have already informed them, and as an upstream if you also send a communication to them, then probably it will be taken up promptly.

= = =

**see https://apps.fedoraproject.org/packages/zeroinstall-injector
Fedora 23 which is to be released in october 2015, has still zeroinstall version 2.3** . Even there's "rawhide" (which is supposed to be the  "raw latest imported code" from github repository of 0install) is still having version 2.3 of zeroinstall.
**if nobody informs/take up this issue with fedora then they will continue to ship zeroinstall version 2.3 till the end of civilization. I have already raised with them. If being an upstream if you raise this issue with them, then the users of fedora upcoming versions will atleast have the taste of latest zeroinstall from their official repository.**

= = = 

compare this to debian where:
jessie has version 2.7.3
reference: https://packages.debian.org/jessie/zeroinstall-injector
debian-testing has version 2.8.1
reference:  https://packages.debian.org/testing/zeroinstall-injector

ubuntu vivid (14.04) has 2.8.1
reference: http://packages.ubuntu.com/vivid/zeroinstall-injector

**only fedora is still in love with zeroinstall version "2.3", if 0install upstream (that is core devs ) remind them then only they will take up this case of their totally stale official fedora repository for zeroinstall only.**

**Comment by zaxebo1** [comment]
May be "other major distribution" may also have very stale zeroinstall
**But taking up this issue atleast with fedora is important** , because from this Fedora only - the **RHEL and CentOS** will be taken up.

**Comment by afb** [comment]
The "zeroinstall-injector" package is for the older [Python version](http://www.0install.net/install-python.html), where the latest version *is* 2.3 (2.3.4).
The new package with the [OCaml version](http://www.0install.net/install-source.html) is called "0install", and the latest version there is **2.8** (not .1).

https://apps.fedoraproject.org/packages/0install  ([announcement](http://sourceforge.net/p/zero-install/mailman/zero-install-devel/thread/530A3460.3090705%40fedoraproject.org/#msg32015813))

It still needs to be updated (from 2.6.1), and apparently it is failing to build... But there are bugs already:
* https://bugzilla.redhat.com/show_bug.cgi?id=1070093
* https://bugzilla.redhat.com/show_bug.cgi?id=1239340

But I don't think that 0install will be included in RHEL/CentOS anyway, probably only [EPEL](https://fedoraproject.org/wiki/EPEL) in that case ?

**Comment by afb** [comment]
@zaxebo1: note that the Ubuntu package is called http://packages.ubuntu.com/vivid/0install-core
(there is also a "0install" package, that includes the gtk+ interface too. fedora called it "0install-gui")

**Comment by talex5** [comment]
> It still needs to be updated (from 2.6.1), and apparently it is failing to build... But there are bugs already:

> https://bugzilla.redhat.com/show_bug.cgi?id=1239340

I'm assuming these are the build errors: https://bugzilla.redhat.com/attachment.cgi?id=1046342

    DEBUG util.py:378:  Error: Package: ocaml-curl-0.5.3-17.fc23.i686 (build)
    DEBUG util.py:378:             Requires: ocaml(Obj) = 825c406ee2d12ed12fd12dc0e4de1d26
    DEBUG util.py:378:             Installing: ocaml-runtime-4.02.2-0.rc1.1.fc23.i686 (build)
    DEBUG util.py:378:                 ocaml(Obj) = 8b014ec57a472d9f3922b63e5de9d1f2
    DEBUG util.py:378:  Error: Package: ocaml-camlp4-4.02.1-0.4.gitcf1935d3.fc23.i686 (build)
    DEBUG util.py:378:             Requires: ocaml(Warnings) = 67f8829b16597356d90e126abbb3e949
    DEBUG util.py:378:             Installing: ocaml-compiler-libs-4.02.2-0.rc1.1.fc23.i686 (build)
    DEBUG util.py:378:                 ocaml(Warnings) = 644f347ec032c6c4524d44b97baeb72d

I'm not sure what this means (some Fedora thing, I assume). I'm guessing that their packages have got out of sync somehow, with different libraries compiled against different versions of OCaml.

Perhaps some Fedora user could try compiling it manually and see if it works?

(the main thing it would be nice to fix is that Fedora didn't package the `obus` library, meaning that PackageKit support was broken in the official packages)

**Comment by zaxebo1** [comment]
@afb:
you said that
> there is also a "0install" package, that includes the gtk+ interface too. Fedora called it "0install-gui"

but i searched at
https://apps.fedoraproject.org/packages/s/0install
there is 0install  and zeroinstall-injector package in Fedora, **but there is no "0install-gui" in Fedora as you suggested**

**Comment by afb** [comment]
@talex5: apparently the rpm hasn't built properly in *months*, not since fc21:

http://koji.fedoraproject.org/koji/packageinfo?packageID=18006

@zaxebo1: my bad, it was apparently only in the head of the maintainer:

> Will rework the update to split out -gui and -core in the next update 
(so as to not drag the release process too long). That will give more 
time to update the legacy Python version as well so both can be 
parallel-installed.
> - Michel Alexandre Salim

http://sourceforge.net/p/zero-install/mailman/message/32016727/

Did you try contacting the maintainer ? This is not an upstream thing.
Like Thomas says, looks like the entire OCaml stack needs some love...

Perhaps also http://fedoraproject.org/wiki/SIGs/OCaml ([ocaml-devel](https://admin.fedoraproject.org/mailman/listinfo/ocaml-devel))
https://lists.fedoraproject.org/pipermail/ocaml-devel/2014-January/002263.html

**Comment by zaxebo1** [comment]
@afb 
>  Like Thomas says, looks like the entire OCaml stack needs some love...

this native ocaml stack packaging problems in some distributions, is where the **ocamljava** based compilation support of 0install source code, would have been a great single file dropin solution, which will work in every case.Currently  it is really a headache , when one works simultaneously across various distributions.

**Comment by afb** [comment]
You would have same problem with java, only worse (trying to interface with dbus and gtk+ from java)
We *do* have a single-file solution, but that is not what Fedora wants - it needs to build from source...

http://0install.net/tools/0install.xml
> Download the appropriate archive for your system, unpack it, and run the install.sh script inside. You'll need libcurl installed (most systems have it by default).

**Comment by talex5** [comment]
Looks like this got fixed:
```
$ dnf search --showduplicates 0install
Last metadata expiration check: 0:00:59 ago on Fri 01 Jun 2018 05:00:29 PM BST.
======================================== Name Exactly Matched: 0install ========================================
0install-2.12.1-1.fc27.x86_64 : A decentralized cross-distribution software installation system
```
