### ISSUE TITLE
FreeBSD support broken

### ISSUE THREAD

**Issue by ysangkok** [0install/0install#45]
The first hurdle can be overcome by using `$(MAKE)` (using the same make that was used by the user) instead of `make` in the root `Makefile`. But then `ocaml/build-in.ml` calls `make`, which defaults to the FreeBSD make, which runs `ocaml/Makefile`. In this file, the if syntax is GNU specific.

**Comment by talex5** [comment]
Thanks for the report. I don't use FreeBSD, but patches are welcome!

**Comment by talex5** [comment]
Perfect - thanks!
