### ISSUE TITLE
Portable mode via environment variable

### ISSUE THREAD

**Issue by bastianeicher** [0install/0install#50]
The Windows version of Zero Install supports a [portable mode](http://0install.de/about/portable) where
* `%appdata%\0install.net`/`$XDG_CONFIG_HOME/0install.net` is replaced by `$ZEROINSTALL_PORTABLE_BASE/config`,
* `%localappdata%\0install.net`/`$XDG_DATA_HOME/0install.net` is replaced by `$ZEROINSTALL_PORTABLE_BASE/data` and
* `%localappdata%\0install.net`/`$XDG_CACHE_HOME/0install.net` is replaced by `$ZEROINSTALL_PORTABLE_BASE/cache`.

The portable mode is activated by placing a file named `_portable` in the installation directory. Zero Install for Windows then passes this "portable state" on to external processes by setting the environment variable `ZEROINSTALL_PORTABLE_BASE` to the installation directory.

Support for this environment variable would need to be added to the OCaml implementation so that it can be used as an external solver by the Windows implemnentation when running in portable mode.

**Comment by bastianeicher** [comment]
Bump

**Comment by talex5** [comment]
Don't we already support this? The man-page says:

       ZEROINSTALL_PORTABLE_BASE

              If this is set, then the XDG_ variables are ignored  and  the  configuration  and  cache  are  stored  in
              $ZEROINSTALL_PORTABLE_BASE/config and $ZEROINSTALL_PORTABLE_BASE/cache instead.

**Comment by bastianeicher** [comment]
Last time I checked I couldn't find any references to `ZEROINSTALL_PORTABLE_BASE` in the OCaml port but I guess I just wasn't looking properly. :grin:

There is still one difference though: If I'm reading the code correctly the OCaml version uses paths like `$ZEROINSTALL_PORTABLE_BASE/cache/0install.net/implementations` while the C# version uses `$ZEROINSTALL_PORTABLE_BASE/cache/implementations`.

**Comment by talex5** [comment]
Hmm, it's the same behaviour as the Python version...

**Comment by bastianeicher** [comment]
I just did a little Git archaeology: The [private fork of the Python solver](/bastianeicher/0install/tree/solver) currently used by Zero Install for Windows contains the commit 4ddf361ec5cc819394a99bec32ab13d9b093596c, which trims `0install.net` out of file paths in portable mode. This commit never got merged into master.

Would you consider porting this functionality to the OCaml implementation?

**Comment by talex5** [comment]
OK, I've changed it. I think the Windows port was the only thing using this. The patch is quite small (mainly the tests), because I did a bit of refactoring first.

One related change: the portable base previously affected everything at the XDG level, including searching for .desktop files in `$XDG_DATA_DIRS/applications`. Now, it only affects 0install paths, which seems more logical.

**Comment by bastianeicher** [comment]
That's great, thanks. :)
