### ISSUE TITLE
Tutorial depends on broken 0publish-gui?

### ISSUE THREAD

**Issue by sam-falvo** [0install/0install#54]
I tried starting out with this tutorial:  http://0install.net/packaging-binaries.html#idp170048

When I got to the point of installing 0publish-gui with `0install add 0publish-gui http://0install.net/2007/interfaces/0publish-gui.xml`, it froze trying to download readline6.  After about 15 minutes, I just CTRL-C'd it, and re-ran the command.  It does not even try to resume with readline6; rather it now freezes completely on ROX-Lib.

I was hoping to explore using 0install to function as a package distribution and modularization mechanism for my project (https://github.com/kestrelcomputer/kestrel), particularly to package development tools and the emulator components.

I'm running Ubuntu 15.04.  Any help would be appreciated, but I suspect there's something wrong with the XML file behind 0publish-gui, and I'm not sure what I can do to fix things.

**Comment by talex5** [comment]
If you run with `-v` (or `-vv`) you should get some information about what it's doing. To redownload the metadata, with (very) verbose output:

    0install select -rvv http://0install.net/2007/interfaces/0publish-gui.xml

Probably readline wasn't needed for the version selected, so not having it wasn't fatal. If you're using the GUI, you can click "Run" anyway in that case.

However, you might be better off with the (non-GUI) [0template](http://0install.net/0template.html). That's what I'm using these days. 0publish-gui uses libglade which is unreliable on modern systems, although it seems to be working OK here (Debian 8).

**Comment by sam-falvo** [comment]
It produces this output, then just sits there indefinitely.

https://gist.github.com/sam-falvo/d04f67ffb8adbd34acbf

**Comment by talex5** [comment]
That's odd. It didn't even update the status line showing what it was waiting for next. However, it worked for me when I tried it in an Ubuntu 15.04 Docker container.

(although apt-cache was super-slow... but that looks like https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1332440)

One other thing you could try: does it work with the generic binary? e.g.

    $ 0install --version
    0install (zero-install) 2.8

    $ 0install add 00install http://0install.net/tools/0install.xml
    $ 00install --version
    0install (zero-install) 2.10

    $ 00install select -rvv http://0install.net/2007/interfaces/0publish-gui.xml

**Comment by sam-falvo** [comment]
I cannot even get past the first add.  :(  https://gist.github.com/sam-falvo/33586f1702d8a0eb0ea6

```
kc5tja@enif:~$ 0install --version
0install (zero-install) 2.8
Copyright (C) 2013 Thomas Leonard
This program comes with ABSOLUTELY NO WARRANTY,
to the extent permitted by law.
You may redistribute copies of this program
under the terms of the GNU Lesser General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by talex5** [comment]
Could you try getting it directly?

    $ apt-get install libcurl3 wget
    $ wget https://downloads.sourceforge.net/project/zero-install/0install/2.11/0install-linux-x86_64-2.11.tar.bz2
    $ ./0install-linux-x86_64-2.11/files/0install --version
    0install (zero-install) 2.11

Also, what does `sudo netstat -tpn` show when it's waiting?

**Comment by sam-falvo** [comment]
wget on the link above worked.  To provide data for the `netstat -tpn` command, I started a 0install select -rvv on the publishing tool, and invoked the command twice.  Here is the results I received:

```
kc5tja@enif:~$ sudo netstat -tpn
[sudo] password for kc5tja: 
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.1.114:50753     192.241.178.125:443     ESTABLISHED 20232/firefox   
tcp        1      0 192.168.1.114:58108     216.34.181.96:80        CLOSE_WAIT  20532/0install  
tcp        0      0 192.168.1.114:41405     74.125.224.9:443        ESTABLISHED 20232/firefox   
tcp        1      0 192.168.1.114:58887     91.189.89.144:80        CLOSE_WAIT  29153/ubuntu-geoip-
tcp        0      0 192.168.1.114:37162     74.125.28.189:443       ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:46162     173.194.68.94:443       ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:39871     216.34.181.97:80        ESTABLISHED 20532/0install  
tcp        0      0 192.168.1.114:39870     216.34.181.97:80        ESTABLISHED 20532/0install  
tcp        0      0 192.168.1.114:49030     166.78.62.138:22        ESTABLISHED 20047/ssh       
tcp        0      0 192.168.1.114:41407     74.125.224.9:443        ESTABLISHED 20232/firefox   
tcp6       1      0 ::1:49856               ::1:631                 CLOSE_WAIT  4650/cups-browsed
tcp6       1      0 ::1:49800               ::1:631                 CLOSE_WAIT  4650/cups-browsed
tcp6       1      0 ::1:49665               ::1:631                 CLOSE_WAIT  9419/indicator-prin
kc5tja@enif:~$ sudo netstat -tpn
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.1.114:39074     23.235.47.133:443       ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:50753     192.241.178.125:443     ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:58256     192.30.252.87:443       ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:54716     172.217.0.78:443        ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:39075     23.235.47.133:443       ESTABLISHED 20232/firefox   
tcp        1      0 192.168.1.114:58108     216.34.181.96:80        CLOSE_WAIT  20532/0install  
tcp        1      0 192.168.1.114:58887     91.189.89.144:80        CLOSE_WAIT  29153/ubuntu-geoip-
tcp        0      0 192.168.1.114:37162     74.125.28.189:443       ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:38786     172.217.0.78:80         ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:40201     199.27.79.133:443       ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:39871     216.34.181.97:80        ESTABLISHED 20532/0install  
tcp        0      0 192.168.1.114:52315     54.85.147.14:443        ESTABLISHED 20232/firefox   
tcp        0      0 192.168.1.114:39870     216.34.181.97:80        ESTABLISHED 20532/0install  
tcp        0      0 192.168.1.114:49030     166.78.62.138:22        ESTABLISHED 20047/ssh       
tcp        0      0 192.168.1.114:40200     199.27.79.133:443       ESTABLISHED 20232/firefox   
tcp6       1      0 ::1:49856               ::1:631                 CLOSE_WAIT  4650/cups-browsed
tcp6       1      0 ::1:49800               ::1:631                 CLOSE_WAIT  4650/cups-browsed
tcp6       1      0 ::1:49665               ::1:631                 CLOSE_WAIT  9419/indicator-prin
```

**Comment by talex5** [comment]
And what happens if you use the new 0install binary to download things? e.g.

    ./0install-linux-x86_64-2.11/files/0install select -rvv http://0install.net/2007/interfaces/0publish-gui.xml

I'm curious because I see Ubuntu is still shipping libocurl-ocaml 0.5.3-2build4, and 0install switches to a different code path for versions older than 0.7.1 (released May 12, 2014).

If it still hangs, please send the strace output:

    strace ./0install-linux-x86_64-2.11/files/0install select -rvv http://0install.net/2007/interfaces/0publish-gui.xml

**Comment by talex5** [comment]
(to clarify: the generic binary bundles a newer copy of libocurl-ocaml)

**Comment by sam-falvo** [comment]
YAY!!  The latest version seems to work!!  (At least when I installed it in $HOME)  Thanks!!  I'll open a separate GH issue if I have additional problems, but I *think* this will let me continue with the online tutorial.

I figure once I've gone through the tutorial and played around a bit, I'll move on to using 0template and 0repo directly.

Thanks again!
