### ISSUE TITLE
Environment variables for .NET and OCaml integration

### ISSUE THREAD

**Issue by bastianeicher** [0install/0install#55]
The Python version of Zero Install used to detect two environment variables set by the .NET code:

`ZEROINSTALL_EXTERNAL_STORE` which points to a command that takes paths to archives to extract. Useful to support `0install store add DIGEST ARCHIVE` on Windows.

`ZEROINSTALL_EXTERNAL_FETCHER` which points to a command that accepts an <implementation> XML snippet on stdin to download and add to the cache.  Useful to support `0install download|update|run URI` on Windows.

It seems the OCaml version only supports `ZEROINSTALL_EXTERNAL_FETCHER`. Perhaps `ZEROINSTALL_EXTERNAL_STORE` should also be ported for completeness' sake?

**Comment by talex5** [comment]
It seems that the Python version only handled `<archive>` steps. Perhaps we should implement a better interface? e.g. send the whole `<recipe>` to .NET and let it do the downloads?

**Comment by bastianeicher** [comment]
Actually `ZEROINSTALL_EXTERNAL_FETCHER` does just that. It takes entire `<implementation>`s and downloads them.

But I believe the older, less capable `ZEROINSTALL_EXTERNAL_STORE` that only handles archives still has its use for the `0install store add` use case.
