### ISSUE TITLE
problem with libcurl (7.49.1)

### ISSUE THREAD

**Issue by icy** [0install/0install#56]
I download `0install-2.11` and try them on an ArchLinux machine. Here is the error message

```
ldd 0install
./0install: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./0install)
```

There is `curl 7.49.1` on my system.

**Comment by talex5** [comment]
Does installing this package help? https://aur.archlinux.org/packages/libcurl-compat/

**Comment by icy** [comment]
Hi @talex5,

Thanks for your helps.

I think that would help, and I will give it a try. However I don't really like to install any AUR package on my system (it just makes future maintainance a bit hard).

**Comment by talex5** [comment]
OK. Let me know and I'll update the instructions for Arch if it works.

Long-term, the solution is probably to switch from libcurl to cohttp for the generic binary.

**Comment by talex5** [comment]
Instructions are now updated: http://0install.net/install-linux.html
