### ISSUE TITLE
0install fails on ArchLinux

### ISSUE THREAD

**Issue by mildred** [0install/0install#58]
There is no precompiled package for ArchLinux, so I tried to use 0install to install 0install (bootstrap). I downloaded the latest version of 0install and made sure that the default python version in PATH was python2. I added the files directory (that contains all the 0install binaries) to the PATH.

Then, I wanted to install 0install by:

    0install -c add 0install http://0install.net/tools/0install.xml

I got:
```
[net/tools/0install.xml] [idus.com/lib/readline6] [idus.com/python/python] [/python/python-gobject] [on/python/upstream.xml] [dus.com/security/gnupg] 
Traceback (most recent call last):
  File "/home/mildred/.local/opt/0install-linux-x86_64-2.4-rc1/files/zeroinstall/cmd/slave.py", line 343, in handle_invoke
    response = do_get_package_impls(config, options, request[1:], xml)
  File "/home/mildred/.local/opt/0install-linux-x86_64-2.4-rc1/files/zeroinstall/cmd/slave.py", line 136, in do_get_package_impls
    feed = config.iface_cache.distro.get_feed(master_feed)
  File "/home/mildred/.local/opt/0install-linux-x86_64-2.4-rc1/files/zeroinstall/injector/distro.py", line 229, in get_feed
    self.get_package_info(package, factory)
  File "/home/mildred/.local/opt/0install-linux-x86_64-2.4-rc1/files/zeroinstall/injector/distro.py", line 891, in get_package_info
    name, version, build = entry.rsplit('-', 2)
ValueError: need more than 1 value to unpack
... solving for interface http://0install.net/tools/0install.xml
```

Debugging this, I found that it seems to be a problem with the native ArchLinux package manager. In the code (distro.py get_package_info):

    self._packages_dir = "/var/lib/pacman/local"
    entry = "ALPM_DB_VERSION"
    result of entry.rsplit(...) = ['ALPM_DB_VERSION']

This is because in the directory `/var/lib/pacman/local`, beside all the installed package, there is a `ALPM_DB_VERSION` file. I think we should ignore files that cannot be split to three components.

My fix is:

```
--- /home/mildred/.local/opt/0install-linux-x86_64-2.4-rc1/files/zeroinstall/injector/distro.py.old	2017-05-17 10:27:25.029524901 +0200
+++ /home/mildred/.local/opt/0install-linux-x86_64-2.4-rc1/files/zeroinstall/injector/distro.py	2017-05-17 10:28:00.590517009 +0200
@@ -884,7 +884,10 @@
 		# Add installed versions...
 		"""@type package: str"""
 		for entry in os.listdir(self._packages_dir):
-			name, version, build = entry.rsplit('-', 2)
+			split = entry.rsplit('-', 2)
+			if len(split) != 3:
+				continue
+			name, version, build = split
 			if name == package:
 				gotarch = False
 				# (read in binary mode to avoid unicode errors in C locale)
```

**Comment by talex5** [comment]
The Python version is pretty old now. I managed to get the new version installed in an Arch Docker container though, and I updated the instructions at http://0install.net/install-linux.html#arch - does that work for you?
