### ISSUE TITLE
Offer a precompiled binary

### ISSUE THREAD

**Issue by vitiral** [0install/0install#59]
I really like the ideas behind this tool, but I am having an impossible time actually installing it on an arch linux system.

It should be an abosolute requirement that this software is compiled to a statically linked binary with no dependencies. Having a tool that is supposed to make installation easy be *itself* difficult to install really hurts it.

Is this possible/easy in OCaml?

**Comment by talex5** [comment]
Ah. These instructions don't work any more then?
http://0install.net/install-linux.html#arch

OCaml itself is statically linked, but 0install uses libcurl and openssl, which are C libraries. It would be possible to replace these with cohttp and ocaml-tls, but you still need some way to find the distribution's approved CA certificates list (which will be different for every distribution, I suspect). It would also mean losing ftp support, although I'm not sure anyone still needs that. Building on Alpine might make static linking easier too (removes glibc problems at least).

I don't have time to work on it at the moment, but it would be nice indeed.

**Comment by vitiral** [comment]
Is there no way to statically link to those libraries? If it could all be compiled into a single binary that would be best.

If there isn't that possibility, I would say removing ftp support for the sake of a single binary would be well worth it. At least ship it as the "main" version and offer some path to additional features for those who need it.

I was expecting the installation for 0install to be:
- download and unpack a tarball
- verify a signature if you want
- put the `0install` binary somewhere on your `PATH`

Also, I should point out that I was evaluating this tool as a possible path for "standard" distribution of rust binaries: http://vitiral.github.io/2017/09/01/distribution-of-rust-binaries.html

Based on my experience so far, I'm thinking of writing my [own tool](https://github.com/vitiral/wpkg) for this purpose. I personally would prefer a json blob for the release information and metadata, rather than what it seems to be from the docs of "a website that has links in this specific format". That's just personal preference though, and I'm sure such a feature could be added to 0install to support that use case.

Sorry if I am being a contrarian -- I really like the design and goals of the tool, I just think there are some things that could be improved!

**Comment by bastianeicher** [comment]
@vitiral: For clarification: "a website that has links in this specific format" just means a machine-readable XML file that also has an XSLT stylesheet that makes it look nice in a browser. It is not intended to mean an HTML file that includes additional hidden XML.

In 0install jargon this sort of XML file is called a "feed". Have a look at http://repo.roscidus.com/java/maven and see what the browser shows you when you select "show source".

Using XML rather than JSON does offer quite a few advantages IMHO:
- Extensibility using XML namespaces: Tools like [0compile](http://0install.net/0compile.html) can store information in Zero Install feeds in their own namespace without influencing 0install's behavior.
- Human- and machine-readable form in same document: Using the aforementioned stylesheet.
- Easier representation of inheritance: 0install feeds have polymorphic lists for things like retrieval methods (`<archive>`, `<file>`, ...) and bindings (`<environment>`, `<executable-in-path>`, ...). Expressing this sort of thing in JSON is usually rather cumbersome.

**Comment by vitiral** [comment]
thanks @bastianeicher. I can see the benefits of xml in a feed file, as a packager and developer I just prefer the json format.

However, I've been pouring over other solutions in this space and have hit upon the [Nix package manager](https://nixos.org/nix/) as the main solution I will be using and developing for.

Again, really like the tool but probably won't be using personally. Feel free to close this issue if you would like.

**Comment by bastianeicher** [comment]
@vitiral: There are already precompiled binaries available. They are listed in the [0install feed for 0install](http://0install.net/tools/0install.xml) (kind of meta ;) ).

Here's a deep-link to the current build: https://downloads.sourceforge.net/project/zero-install/0install/2.12.1/0install-linux-x86_64-2.12.1.tar.bz2

**Comment by bastianeicher** [comment]
@vitiral: Nix and 0install do indeed share a lot of design goals. One thing worth mentioning is that 0install has pretty comprehensive Windows support (including handling start menu entries, file associatiations, etc.) whereas Nix only supports Linux and macOS.

**Comment by vitiral** [comment]
it seems to still depend on my system libcurl:

```
$ tar xf 0install-linux-x86_64-2.12.1.tar.bz2                                                                                                                                                           
$ cd 0install-linux-x86_64-2.12.1/files  
$ 0install -h
files/0install: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by files/0install) 
```

**Comment by vitiral** [comment]
I've heard reports that it is starting to work on windows-bash. But ya, it's probably not ever going to have start-menu and file associans. That's pretty cool!

0install is a pretty cool tool, but I have a hard time preaching a tool that I can't install :) I'll keep my eye on it. When all I want is to distribute a pre-compiled binary this is exactly the kind of thing I *want* to reach for!

**Comment by bastianeicher** [comment]
Thanks for trying out the binary and reporting back.

One last idea: Perhaps installing `libcurl-compat` via Pacman and running `$ LD_PRELOAD=libcurl.so.3 ./0install` will help.

**Comment by vitiral** [comment]
I swear I tried that before and it failed, but it just worked!

I'm going to try a few different things. I literally *just* started having issues with even the *build* of my application because of some cross compilation flags necessary for openssl compilation. I'm going to be setting up a full Nix environment, but I think I also want to support 0install as well. Thanks for the help, feel free to close.

One note: I think it would be a good idea to put the full binary link front and center on your docs, or even have a script for installing it. Having a linux/osx method of installation similar to [rustup](https://www.rustup.rs/) should be the goal (for rustup you literally just run `curl https://sh.rustup.rs -sSf | sh` and BAM it's installed).

**Comment by vitiral** [comment]
also, do you have a more long term solution except for me creating alias for all the 0install commands to prefix that? I also don't want to set an env variable. Also, is there plans to load the correct libcurl more intelligently so that env-variable isn't necessary?

Thanks!

**Comment by talex5** [comment]
BTW, the current binaries are created using these Dockerfiles:

  https://github.com/talex5/docker-builders

If anyone has some time to figure out how to create a Dockerfile that generates statically linked binaries, that would be great.

I'm still a bit concerned about the CA file though (whatever TLS library we use). If we bundle one, it will become out-of-date. If we don't, we'll have to figure out where it lives on each Linux distro individually.

**Comment by vitiral** [comment]
I think for an application like this it should be fine. *By its nature* applications like this should be updated frequently, since they are updated out of sync with the distro's package manager.

Ya, using past versions will introduce security vulnerabilities... but that's true for almost any software.

Just my 2c

**Comment by talex5** [comment]
The 0install 2.15 binary at http://0install.net/injector.html#linux-generic now works with archlinux (it no longer uses libcurl). Tested using today's `archlinux` image on Docker Hub.
