### ISSUE TITLE
Mac package is outdated and corrupt

### ISSUE THREAD

**Issue by constfun** [0install/0install#74]
I've visited the home page and downloaded 0install clicking the big green button. This gave me http://downloads.sourceforge.net/project/zero-install/0install/2.8/ZeroInstall.pkg which is quite outdated, I think.

Upon running the file I get a message from macOS 
`"Zeroinstall.pkg" is damaged and can't be opened. You should move it to the Trash.`

I've tried downloading it multiple times, same result.

I'm on Sierra 10.12.5

**Comment by talex5** [comment]
I think this is just macOS's way of saying that it doesn't trust it. I tried it on a High Sierra Mac and it worked, although I had to use the right-click menu to open it with Installer (it refused to let me run it directly).

**Comment by afb** [comment]
I don't run Mac anymore, so have not been able to update the pkg (nor the dependencies, like gtk+)

**Comment by talex5** [comment]
I added an action here to build master and publish the resulting archive: https://github.com/0install/0install/actions

Maybe a mac user could test this and (if necessary) turn this into a proper mac package.

**Comment by bastianeicher** [comment]
I've uploaded a [copy of the ZIP archive](https://0install.de/files/0install-macos-latest.zip) because the GitHub Actions build artifacts only seem to be downloadable by project contributors.

I also noticed that the ZIP archive generated by GitHub Actions does not seem to preserve executable bits. I got it working in a CI pipeline like this:

    curl -slO https://0install.de/files/0install-macos-latest.zip
    unzip 0install-macos-latest.zip -d 0install
    chmod +x 0install/files/0install
    ./0install/files/0install --help

@morevnaproject Could you perhaps help us out with testing this a little more thoroughly on a Mac?

**Comment by morevnaproject** [comment]
> I've uploaded a copy of the ZIP archive because the GitHub Actions build artifacts only seem to be downloadable by project contributors.

Thank you! I also can access build artifacts from this link ^__^ - https://github.com/0install/0install/actions/runs/71248591

> I also noticed that the ZIP archive generated by GitHub Actions does not seem to preserve executable bits.

Yes, this is a specific of ZIP format - it doesn't preserve execution attributes and any other *nix-like attributes. For keeping execution bits it wil work to pack into tar.gz or tar.bz2 ^__^

> @morevnaproject Could you perhaps help us out with testing this a little more thoroughly on a Mac?

I tested and got the following error:
![screenshot_001](https://user-images.githubusercontent.com/332868/79044334-b8dc3300-7c2e-11ea-943b-ed51b01af2bf.png)

It looks like my version of OSX (10.10) is too old for that.
[This link](https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners) says that GitHub actions use OSX 10.15.

Building on older version of OSX can solve the issue. TravisCI offer OSX version 10.10 for building packages.

**Comment by bastianeicher** [comment]
Issue superseded by #182
