### ISSUE TITLE
Gentoo package names (containing slashes) rejected

### ISSUE THREAD

**Issue by bastianeicher** [0install/0install#80]
Gentoo package names, like `sys-devl/gettext` (containing slashes) are rejected with a message like:

    Ignoring invalid distribution package name 'sys-devl/gettext'

Originally reported by @pmiess in 0install/0install-win#114.

**Comment by talex5** [comment]
That's odd. The code allows it:

https://github.com/0install/0install/blob/master/ocaml/zeroinstall/distro_impls.ml#L901

And the tests seem to use slashes:

https://github.com/0install/0install/blob/868a0aa813f05b1b0ccdcbdae9fd25a75c57f6f1/ocaml/tests/test_distro.ml#L140

Perhaps the distribution attribute is missing, so it doesn't know this is for Gentoo? Do you have an example?

**Comment by bastianeicher** [comment]
Sample feed provided by @pmiess: https://pmiess.gitlab.io/0install-feeds/gnuwin32/giflib.xml

The element in question is `<package-implementation distributions="Gentoo" package="media-libs/giflib"/>`.

**Comment by talex5** [comment]
Works for me:

```
docker create -v /usr/portage --name myportagesnapshot gentoo/portage:latest /bin/true
docker run --rm -it --volumes-from myportagesnapshot gentoo/stage3-amd64:latest /bin/bash
emerge net-misc/curl
emerge app-crypt/gnupg
emerge media-libs/giflib
wget https://downloads.sourceforge.net/project/zero-install/0install/2.12.3/0install-linux-x86_64-2.12.3.tar.bz2
tar xf /0install-linux-x86_64-2.12.3.tar.bz2
./0install-linux-x86_64-2.12.3/install.sh local
0install select --command= https://pmiess.gitlab.io/0install-feeds/gnuwin32/giflib.xml
```

Gives:
```
0install: /usr/lib64/libcurl.so.4: no version information available (required by 0install)
Feed: https://pmiess.gitlab.io/0install-feeds/gnuwin32/giflib.xml                                           
The feed is correctly signed with the following keys:
- 6A66E9E5CA43E23F678478B96ABB34B516AD1160
Warning: Nothing known about this key!
Do you want to trust this key to sign feeds from 'pmiess.gitlab.io'?
[Y/N] y
- URI: https://pmiess.gitlab.io/0install-feeds/gnuwin32/giflib.xml
  Version: 5.1.4
  Path: (package:gentoo:media-libs/giflib:5.1.4:x86_64)

```

**Comment by talex5** [comment]
(the message you mention may appear on other distributions as the name isn't valid there, but it's just a log message and only shown with verbose logging on)

**Comment by pmiess** [comment]
The message appears on windows, I don't see why it would complain that Gentoo package names are not valid when they are on Gentoo.

**Comment by talex5** [comment]
It's not complaining, it's just saying that it's ignoring it because it's not a valid name (on the host platform):

```
info: Ignoring invalid distribution package name 'media-libs/giflib'
```

Maybe it should add `(for host platform)` or something.
