### ISSUE TITLE
Document runtime dependency on libcurl

### ISSUE THREAD

**Issue by bastianeicher** [0install/0install#84]
I tried to bootstrap the current version of 0install (2.12.3) using the Ubuntu 16.04.4 LTS packaged version of 0install (2.10) and got an error:

```
$ 0install run http://0install.net/tools/0install.xml --version
.../.cache/0install.net/implementations/sha256new_KMBP7THWUG6NKNIWNRRV3OLUMQZIOQCMIY4F4ST537W4ROARATVQ/files/0install: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

This was easily fixed with `apt install libcurl3` but maybe it would be a good idea to document the runtime dependency on libcurl, since it seems to be the only lib missing for bootstrapping on a vanilla Ubuntu.

**Comment by talex5** [comment]
Good idea. I've added a note to the generic binaries section: https://0install.net/install-linux.html#generic
