### ISSUE TITLE
fix for  "`CURL_OPENSSL_3' not found (required by 0install)"   in manjaro-Linux

### ISSUE THREAD

**Issue by KM-200** [0install/0install#91]
$ 0install 
0install: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by 0install)
errorcode 1
# so do not do this, instead do the following in bash:

 LD_PRELOAD=/usr/lib/libcurl.so.3    0install 
# this , on the other hand, works nicely !

**Comment by talex5** [comment]
The 2.15 generic binaries no longer use libcurl, so this should now be fixed.
